name: Version Bump

on:
  pull_request:
    branches:
      - main

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Bump version and push
        run: |
          # Choose your bump type: patch, minor, or major
          npm version patch
          git push --follow-tags

        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
