name: Version Bump

on:
  push:
    branches:
      - dev

jobs:
  bump_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Check for changes and commit/stash
        run: |
          if [[ $(git status --porcelain) ]]; then
            git stash push --include-untracked
          fi
          
      - name: Configure Git User
        run: |
          git config --global user.email "samofalov.19982805@gmail.com"
          git config --global user.name "SamofAnt"

      - name: Bump version and push
        run: |
          # Choose your bump type: patch, minor, or major
          npm version patch
          git config --global user.email "samofalov.19982805@gmail.com"
          git config --global user.name "SamofAnt"
          git push --follow-tags https://github.com/SamofAnt/music-bot.git HEAD:dev
        env:
          GH_TOKEN: secrets.GH_TOKEN
